apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://localhost:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: "my-org"
      defaultBucket: "proxmox"
    secureJsonData:
      token: "my-super-secret-auth-token"
